### ISSUE TITLE
MPR window impossible to be enlarged

### ISSUE THREAD

**Issue by vicentiniluca90** [bettar/miele-lxiv#22] opened 2015-08-18 10:02 UTC
I have an issue opening the MPR window using Yosemite 10.10. It remains with small dimensions compare to my screen even when I tried to zoom in or to fit it to the screen. I tried any possible solution in the "Window" menu (I also attempted the double screen configuration) but the MPR window maintain always the same small size with no possibility to be enlarged (the size in the sample picture below).
Anyone with the same issue or with a solution to this problem?

<img width="1280" alt="screen shot 2015-08-18 at 11 53 14" src="https://cloud.githubusercontent.com/assets/13849176/9327252/bfb481d4-459f-11e5-8ead-0ddc865b5ab4.png">

**Comment by bettar** [comment] 2015-08-24 03:50
The issue is confirmed. It was okay until version b14, then since version b15 the MPR window cannot be resized as you describe. It's not apparently obvious why, as the related Interface Builder code hasn't changed. Maybe when the application was built with a more recent version of Xcode some window layout constraints were interpreted differently. Just a guess. The issue should be investigated.

**Comment by efnikos2000** [comment] 2015-09-22 06:51
I have the same issue with mpr, but i noticed that the 3d curved mpr is working normally.

**Comment by bettar** [comment] 2019-10-02 13:54
The fix will be included in the next release, expected early Oct 2019

**Closed as completed** 2019-10-10 08:38 UTC
